package View;

import Controller.Controller;
import Model.Currency;
import Model.Money;
import java.util.List;

public class Window extends javax.swing.JFrame  implements Dialog, Display{

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fldAmount = new javax.swing.JTextField();
        cbxFrom = new javax.swing.JComboBox<>();
        cbxTo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnlAns = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fldAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldAmountActionPerformed(evt);
            }
        });

        cbxFrom.setModel(new javax.swing.DefaultComboBoxModel<>(currenciesString));
        cbxFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFromActionPerformed(evt);
            }
        });

        cbxTo.setModel(new javax.swing.DefaultComboBoxModel<>(currenciesString));
        cbxTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxToActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 255, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Currency Conversor");
        jLabel1.setMinimumSize(new java.awt.Dimension(105, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("From:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("To:");
        jLabel3.setPreferredSize(new java.awt.Dimension(16, 16));

        jScrollPane2.setViewportView(pnlAns);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(fldAmount)
                    .addComponent(cbxFrom, 0, 152, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxTo, 0, 153, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(fldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFromActionPerformed
        this.controller.updateData();
    }//GEN-LAST:event_cbxFromActionPerformed

    private void cbxToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxToActionPerformed
        this.controller.updateData();
    }//GEN-LAST:event_cbxToActionPerformed

    private void fldAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldAmountActionPerformed
        this.controller.updateData();
    }//GEN-LAST:event_fldAmountActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxFrom;
    private javax.swing.JComboBox<String> cbxTo;
    private javax.swing.JTextField fldAmount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane pnlAns;
    // End of variables declaration//GEN-END:variables

    private final List<Currency> currencies;
    private final Controller controller;
    private final String[] currenciesString;
    
    public Window(List<Currency> currencies, Controller controller) {
        this.currencies=currencies;
        String[] str = new String[currencies.size()];
        for (int i = 0; i < str.length; i++) { str[i] = currencies.get(i).toString(); }
        this.currenciesString = str;
        this.controller=controller;
        initComponents();
    }

    @Override
    public Money getMoney() {
        int option=cbxFrom.getSelectedIndex();
        double total=0;
        try {
            if (fldAmount.getText().length() > 0)
            total = Double.parseDouble(fldAmount.getText());
        } catch (Exception e) {
            return new Money(0, currencies.get(option));
        }
        return new Money(total, currencies.get(option));
    }

    @Override
    public Currency getCurrencyFrom() {
        return currencies.get(cbxFrom.getSelectedIndex());
    }
    
    @Override
    public Currency getCurrencyTo() {
        return currencies.get(cbxTo.getSelectedIndex());
    }
    
    @Override
    public void updateDisplay(Money money) {
        pnlAns.setText(money.toString());
    }
}
